version: "3.9"
services:
    server:
        build: ./server
        ports:
            - "5003:5003"
        volumes:
            - "./server:/app"
    web:
        build: "./frontend-app/frontend"
        ports:
            - "80:3000"
        volumes:
            - "./frontend-app/frontend:/usr/src/app"
        depends_on:
            - server
